### PR TITLE
Found a bug and fixed it by just adding require

### PR DESCRIPTION
**Pull request by robert-senexx**
I don't know why but the current version fails to work with the following error:
`/Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rails-template-cache-0.2.0/lib/rails-template-cache/engine.rb:30:in`block in class:Engine': uninitialized constant RailsTemplateCache::Engine::VERSION (NameError)`

I fixed the error by just adding `require "rails-template-cache/version"` to the engine.rb file.

Can you merge this please?

### CODE REVIEW

**Comment by frm** [comment]
I can't seem to reproduce the issue using the local version of the gem. Moving the `require` to `lib/rails-template-cache.rb` should also fix it. Can you confirm this and move the `require` to that file?

**Comment by robert-senexx** [comment]
I moved the require command and I can confirm this also works :)

**Comment by frm** [comment]
Great! Thank you very much, I'll update the gem.

**Comment by robert-senexx** [comment]
Thanks, it's working great for me now!

On Mon, Feb 29, 2016 at 3:46 PM, Fernando Mendes notifications@github.com
wrote:

> Great! Thank you very much, I'll update the gem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frmendes/rails-template-cache/pull/4#issuecomment-190217501
> .

## 

בברכה,
רובי

**Pull request merged**
